###
GET {{host}}/count

###
POST {{host}}/?studentId=1&courseId=10

###
GET {{host}}/?studentId=1&courseId=10

###
GET {{host}}/count

###
DELETE {{host}}/?studentId=1&courseId=10

###
GET {{host}}/count

